/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.pi.gui.internalframes;

import edu.esprit.pi.dao.DepotDAO;
import edu.esprit.pi.dao.StockDAO;
import edu.esprit.pi.entites.Depot;
import edu.esprit.pi.entites.Stock;
import edu.esprit.pi.gui.tablemodels.StockTableModel;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Amine
 */
public class StockDepotInternFrame extends javax.swing.JInternalFrame {

    // Déclaration de tous les paramètres.
    StockDAO stockDAO = new StockDAO();
    DepotDAO depotDAO = new DepotDAO();
    List<Stock> listStock;
    List<Depot> listDepot;
    Depot depot;
    Stock stock;

    /**
     * Creates new form StockDepotInternFrame
     */
    public StockDepotInternFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hFbuttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        adresseDepotField = new javax.swing.JTextField();
        ajouterDepotButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        prixjTextField4 = new javax.swing.JTextField();
        femmejRadioButton1 = new javax.swing.JRadioButton();
        hommejRadioButton2 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        adresseDepotjComboBox1 = new javax.swing.JComboBox();
        quantitejSpinner1 = new javax.swing.JSpinner();
        ajoutStockjButton1 = new javax.swing.JButton();
        refreshjButton2 = new javax.swing.JButton();
        clearjButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        stockModeljTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        miseaJourjButton3 = new javax.swing.JButton();
        libelleVetjComboBox1 = new javax.swing.JComboBox();
        libellejTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        quitjButton1 = new javax.swing.JButton();
        refrechModeljButton2 = new javax.swing.JButton();
        supprimerjButton = new javax.swing.JButton();

        setTitle("Gestion du Stock");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Gestion du Stock");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Ajout nouveau Depot"));

        jLabel2.setText("Emplacement Dépot");

        ajouterDepotButton.setText("Ajouter");
        ajouterDepotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterDepotButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(adresseDepotField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ajouterDepotButton))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adresseDepotField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addComponent(ajouterDepotButton))
        );

        jLabel3.setText("Libelle vêtement  :");

        jLabel4.setText("Type  :");

        jLabel5.setText("Nombre en stock  :");

        jLabel6.setText("prix  :");

        hFbuttonGroup1.add(femmejRadioButton1);
        femmejRadioButton1.setText("Femme");

        hFbuttonGroup1.add(hommejRadioButton2);
        hommejRadioButton2.setText("Homme");

        jLabel7.setText("Emplacement  :");

        ajoutStockjButton1.setText("Ajouter");
        ajoutStockjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutStockjButton1ActionPerformed(evt);
            }
        });

        refreshjButton2.setText("Raffraichir");
        refreshjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshjButton2ActionPerformed(evt);
            }
        });

        clearjButton3.setText("Effacer");
        clearjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearjButton3ActionPerformed(evt);
            }
        });

        stockModeljTable1.setModel(new StockTableModel());
        jScrollPane1.setViewportView(stockModeljTable1);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("DT");

        miseaJourjButton3.setText("mise à jour");
        miseaJourjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miseaJourjButton3ActionPerformed(evt);
            }
        });

        libelleVetjComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libelleVetjComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adresseDepotjComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(femmejRadioButton1)
                                        .addGap(73, 73, 73)
                                        .addComponent(hommejRadioButton2))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(quantitejSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(prixjTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel8))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(libelleVetjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(libellejTextField1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(clearjButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(miseaJourjButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshjButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ajoutStockjButton1))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(libelleVetjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(libellejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(femmejRadioButton1)
                    .addComponent(hommejRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantitejSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prixjTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adresseDepotjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajoutStockjButton1)
                    .addComponent(refreshjButton2)
                    .addComponent(clearjButton3)
                    .addComponent(miseaJourjButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        quitjButton1.setText("Quitter");
        quitjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitjButton1ActionPerformed(evt);
            }
        });

        refrechModeljButton2.setText("Raffraichir");
        refrechModeljButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrechModeljButton2ActionPerformed(evt);
            }
        });

        supprimerjButton.setText("Supprimer");
        supprimerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(supprimerjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refrechModeljButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quitjButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quitjButton1)
                    .addComponent(refrechModeljButton2)
                    .addComponent(supprimerjButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void remplirAdresseDepotComboBox() {
        listDepot = depotDAO.findAll();
        for (Depot depot : listDepot) {
            adresseDepotjComboBox1.addItem(depot.getAdresse());
        }
    }

    private void remplirStockComboBox() {
        listStock = stockDAO.findAll();
        for (Stock stock : listStock) {
            libelleVetjComboBox1.addItem(stock.getId());
        }
    }
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        remplirAdresseDepotComboBox();
        remplirStockComboBox();
    }//GEN-LAST:event_formInternalFrameOpened

    private void libelleVetjComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libelleVetjComboBox1ActionPerformed
        Stock s = stockDAO.find(Integer.parseInt(libelleVetjComboBox1.getSelectedItem().toString()));
        libellejTextField1.setText(s.getLibelle());
        prixjTextField4.setText(String.valueOf(s.getPrix()));
        quantitejSpinner1.setValue(s.getQtiteStock());
        adresseDepotjComboBox1.setSelectedItem(s.getDepot().getAdresse());
        if (s.getType().equals("Homme")) {
            hommejRadioButton2.setSelected(true);
            femmejRadioButton1.setSelected(false);
        } else {
            hommejRadioButton2.setSelected(false);
            femmejRadioButton1.setSelected(true);
        }
    }//GEN-LAST:event_libelleVetjComboBox1ActionPerformed

    private void ajouterDepotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterDepotButtonActionPerformed
        depot = new Depot();
        depot.setAdresse(adresseDepotField.getText());
        depotDAO.create(depot);
    }//GEN-LAST:event_ajouterDepotButtonActionPerformed

    private void refreshjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshjButton2ActionPerformed
        adresseDepotjComboBox1.removeAllItems();
        remplirAdresseDepotComboBox();
    }//GEN-LAST:event_refreshjButton2ActionPerformed

    private void miseaJourjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miseaJourjButton3ActionPerformed
        stock = new Stock();
        stock.setId(Integer.parseInt(libelleVetjComboBox1.getSelectedItem().toString()));
        stock.setPrix(Double.parseDouble(prixjTextField4.getText()));
        stock.setLibelle(libellejTextField1.getText());
        stock.setQtiteStock(Integer.parseInt(quantitejSpinner1.getValue().toString()));
        if (hommejRadioButton2.isSelected()) {
            stock.setType(hommejRadioButton2.getText());
        } else {
            stock.setType(femmejRadioButton1.getText());
        }
        stock.setDepot(depotDAO.find(adresseDepotjComboBox1.getSelectedItem().toString()));
        stockDAO.update(stock);
    }//GEN-LAST:event_miseaJourjButton3ActionPerformed

    private void ajoutStockjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutStockjButton1ActionPerformed
        stock = new Stock();
        stock.setPrix(Double.parseDouble(prixjTextField4.getText()));
        stock.setLibelle(libellejTextField1.getText());
        stock.setQtiteStock(Integer.parseInt(quantitejSpinner1.getValue().toString()));
        if (hommejRadioButton2.isSelected()) {
            stock.setType(hommejRadioButton2.getText());
        } else {
            stock.setType(femmejRadioButton1.getText());
        }
        stock.setDepot(depotDAO.find(adresseDepotjComboBox1.getSelectedItem().toString()));
        stockDAO.create(stock);
    }//GEN-LAST:event_ajoutStockjButton1ActionPerformed

    private void clearjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearjButton3ActionPerformed
        libellejTextField1.setText("");
        prixjTextField4.setText("50");
        quantitejSpinner1.setValue(10);
        hommejRadioButton2.setSelected(true);
    }//GEN-LAST:event_clearjButton3ActionPerformed

    private void refrechModeljButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrechModeljButton2ActionPerformed
        StockTableModel stm = new StockTableModel();
        stockModeljTable1.setModel(stm);
    }//GEN-LAST:event_refrechModeljButton2ActionPerformed

    private void quitjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitjButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_quitjButton1ActionPerformed

    private void supprimerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerjButtonActionPerformed
        int[] selected = stockModeljTable1.getSelectedRows();
        System.out.println("selected rows " + selected.length);
        List<Stock> toRemove = new ArrayList<Stock>(selected.length);
        for (int i = 0; i < selected.length; i++) {
            Stock s = listStock.get(stockModeljTable1.convertRowIndexToModel(selected[i]));
            System.out.println(s);
            toRemove.add(s);
        }
        System.out.println("La taille de la liste de stock à Supprimer .." + toRemove.size());
        for (Stock s : toRemove) {
            stockDAO.delete(s);
        }
        listStock.removeAll(toRemove);
    }//GEN-LAST:event_supprimerjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresseDepotField;
    private javax.swing.JComboBox adresseDepotjComboBox1;
    private javax.swing.JButton ajoutStockjButton1;
    private javax.swing.JButton ajouterDepotButton;
    private javax.swing.JButton clearjButton3;
    private javax.swing.JRadioButton femmejRadioButton1;
    private javax.swing.ButtonGroup hFbuttonGroup1;
    private javax.swing.JRadioButton hommejRadioButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox libelleVetjComboBox1;
    private javax.swing.JTextField libellejTextField1;
    private javax.swing.JButton miseaJourjButton3;
    private javax.swing.JTextField prixjTextField4;
    private javax.swing.JSpinner quantitejSpinner1;
    private javax.swing.JButton quitjButton1;
    private javax.swing.JButton refrechModeljButton2;
    private javax.swing.JButton refreshjButton2;
    private javax.swing.JTable stockModeljTable1;
    private javax.swing.JButton supprimerjButton;
    // End of variables declaration//GEN-END:variables
}
